#!/usr/bin/env python3
"""Drive one S3 phase: send ZMQ commands to a running FFmpeg graph, log replies.

Every phase writes a JSON record of what was sent, what came back, and when the
reply arrived relative to the first accepted command. The pixel analysis in
analyze_s3.py consumes that record.
"""

from __future__ import annotations

import argparse
import json
import statistics
import time

from ffzmq import TIMEOUT, FFZmq

# (offset seconds after t0, message, human description)
STEPS: list[tuple[float, str, str]] = [
    (0.0, "drawbox@box color 0x00FF00", "drawbox colour red -> green (t0 marker)"),
    (2.0, "eq@eq brightness 0.30", "eq brightness 0.00 -> 0.30"),
    (4.0, "eq@eq saturation 0.20", "eq saturation 1.00 -> 0.20"),
    (6.0, "hue@hue h 120", "hue angle 0 -> 120 deg"),
    (8.0, "drawbox@box color 0x0000FF", "drawbox colour green -> blue"),
    (10.0, "drawbox@box w 160", "drawbox width 100 -> 160 (geometry, not colour)"),
    (12.0, "eq@eq saturation 1.0", "eq saturation restored"),
    (13.0, "hue@hue h 0", "hue restored"),
]

# Ordered so that nothing here can kill the graph; anything suspected of doing
# that belongs in CRASH_CANDIDATES and gets its own FFmpeg process.
REPLY_PROBES: list[tuple[str, str]] = [
    ("valid: instance label", "eq@eq brightness 0.10"),
    ("valid: filter class name", "eq brightness 0.11"),
    ("valid: broadcast target 'all'", "all brightness 0.12"),
    ("addressing: autogenerated Parsed_ name", "Parsed_eq_2 brightness 0.13"),
    ("addressing: bare label without class", "box brightness 0.14"),
    ("error: unknown target", "nosuchfilter brightness 0.1"),
    ("error: unknown command on valid target", "eq@eq nosuchcommand 1"),
    ("error: non-numeric arg", "eq@eq brightness banana"),
    ("error: out-of-range arg (range is -1..1)", "eq@eq brightness 99"),
    ("error: missing arg", "eq@eq brightness"),
    ("boundary: non-commandable option (eq eval)", "eq@eq eval frame"),
    ("boundary: non-commandable option (drawbox box_source)", "drawbox@box box_source x"),
    ("drawbox: colour by name", "drawbox@box color orange"),
    ("drawbox: colour by hex", "drawbox@box color 0x123456"),
    ("drawbox: colour with alpha", "drawbox@box color 0x00FF00@0.5"),
    ("drawbox: alias 'c' instead of 'color'", "drawbox@box c 0x654321"),
    ("drawbox: thickness", "drawbox@box t 8"),
    ("drawbox: geometry expression", "drawbox@box w if(gt(t\\,0)\\,120\\,100)"),
    ("drawbox: colour as an expression (unsupported?)", "drawbox@box color if(gt(t\\,0)\\,red\\,blue)"),
    ("eq: per-channel gamma", "eq@eq gamma_r 1.5"),
    ("eq: expression referencing t", "eq@eq brightness 0.3*sin(2*PI*t)"),
    ("hue: saturation", "hue@hue s 0.5"),
    ("hue: expression referencing t", "hue@hue h mod(t*90,360)"),
    ("zmq: command aimed at the zmq filter itself", "zmq@ctl bind_address tcp://127.0.0.1:1"),
    ("recovery: valid command after all of the above", "eq@eq brightness 0.0"),
]

# Each of these runs against its own FFmpeg process because one of them aborts it.
CRASH_CANDIDATES: list[tuple[str, str]] = [
    ("target_only", "eq@eq"),
    ("empty_message", ""),
    ("whitespace_only", "   "),
    ("target_and_space", "eq@eq "),
    ("arg_with_trailing_token", "eq@eq brightness 0.2 0.3"),
    ("quoted_arg_with_space", "eq@eq brightness '0.2 0.3'"),
    ("unknown_target_only", "nosuchfilter"),
]

# Run in order against one graph: does a single failed command disable the filter?
POISON_SEQUENCE: list[tuple[str, str]] = [
    ("drawbox colour by name", "drawbox@box color orange"),
    ("drawbox colour by hex", "drawbox@box color 0x123456"),
    ("drawbox colour with alpha", "drawbox@box color 0x00FF00@0.5"),
    ("drawbox alias 'c'", "drawbox@box c 0x654321"),
    ("drawbox thickness", "drawbox@box t 8"),
    ("drawbox width", "drawbox@box w 160"),
    ("drawbox geometry expression", "drawbox@box w if(gt(t\\,0)\\,120\\,100)"),
    ("POISON: one command that fails", "drawbox@box box_source x"),
    ("drawbox colour AFTER the failure", "drawbox@box color red"),
    ("drawbox width AFTER the failure", "drawbox@box w 100"),
    ("drawbox thickness AFTER the failure", "drawbox@box t 3"),
    ("eq AFTER the drawbox failure", "eq@eq brightness 0.2"),
    ("hue AFTER the drawbox failure", "hue@hue h 45"),
]


def record(rows: list[dict], out_path: str) -> None:
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(rows, fh, indent=2)


def phase_steps(z: FFZmq, out_path: str) -> None:
    offset, msg, desc = STEPS[0]
    reply, t0 = z.wait_ready(msg)
    rows = [{"t_rel": 0.0, "msg": msg, "reply": reply, "rtt_ms": None, "desc": desc}]
    print(f"t0 established  reply={reply!r}  msg={msg!r}")
    for offset, msg, desc in STEPS[1:]:
        while time.monotonic() < t0 + offset:
            time.sleep(0.002)
        reply, rtt = z.send(msg)
        t_rel = time.monotonic() - t0
        rows.append({"t_rel": t_rel, "msg": msg, "reply": reply,
                     "rtt_ms": rtt * 1000.0, "desc": desc})
        print(f"t+{t_rel:6.3f}s  rtt={rtt * 1000:6.1f}ms  reply={reply!r}  {msg}")
    record(rows, out_path)


def phase_latency(z: FFZmq, out_path: str, steps: int, interval: float) -> None:
    values = [round(-0.35 + 0.05 * i, 3) for i in range(steps)]
    reply, t0 = z.wait_ready(f"eq@eq brightness {values[0]}")
    rows = [{"t_rel": 0.0, "msg": f"eq@eq brightness {values[0]}", "reply": reply,
             "rtt_ms": None, "value": values[0]}]
    for i, val in enumerate(values[1:], start=1):
        while time.monotonic() < t0 + i * interval:
            time.sleep(0.001)
        msg = f"eq@eq brightness {val}"
        reply, rtt = z.send(msg)
        rows.append({"t_rel": time.monotonic() - t0, "msg": msg, "reply": reply,
                     "rtt_ms": rtt * 1000.0, "value": val})
    for r in rows:
        print(f"t+{r['t_rel']:6.3f}s  brightness={r['value']:+.2f}  reply={r['reply']!r}")
    record(rows, out_path)


def phase_replies(z: FFZmq, out_path: str) -> None:
    z.wait_ready("eq@eq brightness 0.0")
    rows = []
    for desc, msg in REPLY_PROBES:
        reply, rtt = z.send(msg)
        rows.append({"desc": desc, "msg": msg, "reply": reply, "rtt_ms": rtt * 1000.0})
        print(f"{desc:52s} | send={msg!r}\n{'':52s} | reply={reply!r}  ({rtt * 1000:.1f} ms)")
    record(rows, out_path)


def phase_throughput(z: FFZmq, out_path: str, count: int) -> None:
    z.wait_ready("eq@eq brightness 0.0")
    rtts = []
    started = time.monotonic()
    for i in range(count):
        _, rtt = z.send(f"eq@eq brightness {0.001 * (i % 100):.3f}")
        rtts.append(rtt * 1000.0)
    elapsed = time.monotonic() - started
    stats = {
        "count": count,
        "elapsed_s": elapsed,
        "commands_per_s": count / elapsed,
        "rtt_ms_min": min(rtts),
        "rtt_ms_median": statistics.median(rtts),
        "rtt_ms_mean": statistics.fmean(rtts),
        "rtt_ms_max": max(rtts),
    }
    for k, v in stats.items():
        print(f"{k:18s} {v:.3f}" if isinstance(v, float) else f"{k:18s} {v}")
    record([stats], out_path)


def phase_ramp(z: FFZmq, out_path: str) -> None:
    # The first command must move a pixel so the analyser can anchor on it.
    reply, t0 = z.wait_ready("eq@eq brightness 0.25")
    rows = [{"t_rel": 0.0, "msg": "eq@eq brightness 0.25", "reply": reply,
             "desc": "static step, anchors the frame timeline"}]
    plan = [
        (2.0, "eq@eq brightness 0.35*sin(2*PI*t/2)",
         "eq brightness driven by a time expression"),
        (7.0, "hue@hue h mod(t*120,360)",
         "hue angle driven by a time expression"),
    ]
    for offset, msg, desc in plan:
        while time.monotonic() < t0 + offset:
            time.sleep(0.002)
        reply, rtt = z.send(msg)
        t_rel = time.monotonic() - t0
        rows.append({"t_rel": t_rel, "msg": msg, "reply": reply,
                     "rtt_ms": rtt * 1000.0, "desc": desc})
        print(f"t+{t_rel:6.3f}s  reply={reply!r}  {msg}")
    record(rows, out_path)


def phase_crashtest(z: FFZmq, out_path: str, name: str) -> None:
    """Send one suspect message, then a canary, and report whether the graph lived."""
    msg = dict(CRASH_CANDIDATES)[name]
    z.wait_ready("eq@eq brightness 0.05")
    suspect, srtt = z.send(msg, timeout_ms=1500)
    canary, crtt = z.send("eq@eq brightness 0.10", timeout_ms=1500)
    alive = canary != TIMEOUT
    row = {"name": name, "msg": msg, "suspect_reply": suspect,
           "suspect_rtt_ms": srtt * 1000.0, "canary_reply": canary,
           "canary_rtt_ms": crtt * 1000.0, "graph_alive": alive}
    print(f"{name:24s} send={msg!r:28s} reply={suspect!r:32s} "
          f"canary={canary!r:14s} -> {'ALIVE' if alive else 'DEAD'}")
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump([row], fh, indent=2)


def phase_poison(z: FFZmq, out_path: str) -> None:
    z.wait_ready("eq@eq brightness 0.0")
    rows = []
    for desc, msg in POISON_SEQUENCE:
        reply, rtt = z.send(msg)
        rows.append({"desc": desc, "msg": msg, "reply": reply})
        print(f"{desc:38s} | {msg:44s} | {reply}")
    with open(out_path, "w", encoding="utf-8") as fh:
        json.dump(rows, fh, indent=2)


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("phase", choices=["steps", "latency", "replies", "throughput",
                                     "ramp", "crashtest", "poison"])
    ap.add_argument("--addr", required=True)
    ap.add_argument("--out", required=True)
    ap.add_argument("--count", type=int, default=150)
    ap.add_argument("--steps", type=int, default=15)
    ap.add_argument("--interval", type=float, default=0.100)
    ap.add_argument("--case", default="")
    args = ap.parse_args()

    z = FFZmq(args.addr)
    try:
        if args.phase == "steps":
            phase_steps(z, args.out)
        elif args.phase == "latency":
            phase_latency(z, args.out, args.steps, args.interval)
        elif args.phase == "replies":
            phase_replies(z, args.out)
        elif args.phase == "throughput":
            phase_throughput(z, args.out, args.count)
        elif args.phase == "crashtest":
            phase_crashtest(z, args.out, args.case)
        elif args.phase == "poison":
            phase_poison(z, args.out)
        else:
            phase_ramp(z, args.out)
    finally:
        z.close()


if __name__ == "__main__":
    main()
